// Advanced-level Bible quiz question bank (50 questions).
// Source: provided "Bible Quiz Advanced" document. Static, no AI calls.
import type { QuizQuestion } from "./types";

export const ADVANCED_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "Which minor prophet was sent to Nineveh and fled in the opposite direction toward Tarshish?",
    options: ["Nahum", "Jonah", "Amos", "Obadiah"],
    answer: 1,
    explanation: "Jonah ran from God’s call to Nineveh and was swallowed by a great fish.",
    reference: "Jonah 1:2-3",
  },
  {
    id: 2,
    question: "Which minor prophet prophesied judgment specifically against Edom, the descendants of Esau?",
    options: ["Joel", "Obadiah", "Habakkuk", "Zephaniah"],
    answer: 1,
    explanation: "Obadiah, the shortest Old Testament book, pronounces doom on Edom.",
    reference: "Obadiah 1:1-4",
  },
  {
    id: 3,
    question: "Which prophet declared, “Let justice roll down like waters, and righteousness like an ever-flowing stream”?",
    options: ["Micah", "Hosea", "Amos", "Haggai"],
    answer: 2,
    explanation: "Amos, a herdsman of Tekoa, condemned injustice in Israel.",
    reference: "Amos 5:24",
  },
  {
    id: 4,
    question: "Which minor prophet foretold that the Messiah would be born in Bethlehem Ephrathah?",
    options: ["Zechariah", "Micah", "Malachi", "Joel"],
    answer: 1,
    explanation: "Micah named Bethlehem as the birthplace of Israel’s ruler.",
    reference: "Micah 5:2",
  },
  {
    id: 5,
    question: "Which post-exilic prophet rebuked the people for building their own houses while God’s temple lay in ruins?",
    options: ["Zechariah", "Haggai", "Malachi", "Nahum"],
    answer: 1,
    explanation: "Haggai urged the returned exiles to rebuild the temple first.",
    reference: "Haggai 1:4-8",
  },
  {
    id: 6,
    question: "Which prophet wrestled with God over why the wicked prosper, and concluded “the just shall live by his faith”?",
    options: ["Habakkuk", "Zephaniah", "Joel", "Nahum"],
    answer: 0,
    explanation: "Habakkuk’s dialogue with God yields the great statement of faith quoted in the New Testament.",
    reference: "Habakkuk 2:4",
  },
  {
    id: 7,
    question: "Which minor prophet closes the Old Testament, foretelling the coming of “Elijah” before the day of the Lord?",
    options: ["Zechariah", "Malachi", "Haggai", "Joel"],
    answer: 1,
    explanation: "Malachi ends the Old Testament with the promise of Elijah before the great day.",
    reference: "Malachi 4:5",
  },
  {
    id: 8,
    question: "In Genesis, who is listed as the father of Methuselah?",
    options: ["Jared", "Enoch", "Lamech", "Mahalalel"],
    answer: 1,
    explanation: "Enoch, who walked with God, was the father of Methuselah.",
    reference: "Genesis 5:21",
  },
  {
    id: 9,
    question: "According to Matthew’s genealogy, the line from Abraham to Christ is divided into sets of how many generations?",
    options: ["Seven", "Ten", "Fourteen", "Twelve"],
    answer: 2,
    explanation: "Matthew structures the genealogy in three sets of fourteen generations.",
    reference: "Matthew 1:17",
  },
  {
    id: 10,
    question: "Which four women are named in Matthew’s genealogy of Jesus before Mary?",
    options: ["Sarah, Rebekah, Rachel, Leah", "Tamar, Rahab, Ruth, and the wife of Uriah (Bathsheba)", "Eve, Miriam, Deborah, Hannah", "Hagar, Keturah, Dinah, Asenath"],
    answer: 1,
    explanation: "Matthew notably includes Tamar, Rahab, Ruth, and Bathsheba.",
    reference: "Matthew 1:3, 5, 6",
  },
  {
    id: 11,
    question: "Through which son of Jacob does the messianic kingly line (David and Jesus) descend?",
    options: ["Joseph", "Levi", "Judah", "Reuben"],
    answer: 2,
    explanation: "The scepter was promised to Judah, the tribe of David and of Christ.",
    reference: "Genesis 49:10",
  },
  {
    id: 12,
    question: "Who was the father of King David, of the tribe of Judah?",
    options: ["Obed", "Jesse", "Boaz", "Nahshon"],
    answer: 1,
    explanation: "David was the youngest son of Jesse of Bethlehem.",
    reference: "1 Samuel 16:1, 11",
  },
  {
    id: 13,
    question: "In Ruth’s genealogy, who was the son of Boaz and Ruth, grandfather of David?",
    options: ["Obed", "Jesse", "Salmon", "Amminadab"],
    answer: 0,
    explanation: "Boaz and Ruth had Obed, the father of Jesse, the father of David.",
    reference: "Ruth 4:17",
  },
  {
    id: 14,
    question: "In Luke’s genealogy, the line is traced back beyond Abraham all the way to whom?",
    options: ["Noah", "Adam", "Enoch", "Seth"],
    answer: 1,
    explanation: "Luke traces Jesus’ line back to Adam, “the son of God,” stressing His link to all humanity.",
    reference: "Luke 3:38",
  },
  {
    id: 15,
    question: "Approximately how many years did the Israelites spend in Egypt before the Exodus, as stated to Abraham?",
    options: ["120 years", "400 years", "70 years", "250 years"],
    answer: 1,
    explanation: "God told Abraham his descendants would be afflicted in a foreign land 400 years.",
    reference: "Genesis 15:13",
  },
  {
    id: 16,
    question: "How long did the Babylonian exile of Judah last, as prophesied by Jeremiah?",
    options: ["40 years", "70 years", "100 years", "430 years"],
    answer: 1,
    explanation: "Jeremiah foretold seventy years of Babylonian captivity.",
    reference: "Jeremiah 25:11",
  },
  {
    id: 17,
    question: "Which empire conquered Babylon and allowed the Jews to return and rebuild under Cyrus?",
    options: ["Assyria", "Persia", "Greece", "Rome"],
    answer: 1,
    explanation: "Cyrus of Persia decreed the Jews’ return to rebuild the temple.",
    reference: "Ezra 1:1-3",
  },
  {
    id: 18,
    question: "In what order did these kingdoms dominate the biblical world from the divided monarchy onward?",
    options: ["Babylon, Assyria, Persia, Greece", "Assyria, Babylon, Persia, Greece", "Persia, Greece, Rome, Babylon", "Greece, Rome, Assyria, Persia"],
    answer: 1,
    explanation: "Assyria fell to Babylon, then Persia, then Greece (with Rome following).",
    reference: "Daniel 2:36-40",
  },
  {
    id: 19,
    question: "Which kingdom fell first: the northern kingdom of Israel or the southern kingdom of Judah?",
    options: ["Judah fell first", "Israel fell first", "They fell together", "Neither fell"],
    answer: 1,
    explanation: "Israel fell to Assyria in 722 BC; Judah fell to Babylon over a century later.",
    reference: "2 Kings 17:6",
  },
  {
    id: 20,
    question: "Roughly how many years separate the Old Testament’s close (Malachi) and the New Testament — the “silent years”?",
    options: ["About 100 years", "About 200 years", "About 400 years", "About 600 years"],
    answer: 2,
    explanation: "Around four centuries passed between Malachi and the events of the Gospels.",
    reference: "Malachi 4:5-6",
  },
  {
    id: 21,
    question: "For how many years did Solomon’s reign last over a united Israel?",
    options: ["20 years", "40 years", "33 years", "70 years"],
    answer: 1,
    explanation: "Solomon reigned forty years before the kingdom divided under his son.",
    reference: "1 Kings 11:42",
  },
  {
    id: 22,
    question: "How many years did it take to build Solomon’s temple in Jerusalem?",
    options: ["Three years", "Seven years", "Twelve years", "Twenty years"],
    answer: 1,
    explanation: "Solomon’s temple was completed in seven years.",
    reference: "1 Kings 6:38",
  },
  {
    id: 23,
    question: "Which feast commemorates Israel’s deliverance from Egypt with the slaying of the lamb?",
    options: ["Pentecost", "Passover", "Tabernacles", "Trumpets"],
    answer: 1,
    explanation: "Passover memorializes the lamb’s blood that spared Israel’s firstborn.",
    reference: "Exodus 12:13-14",
  },
  {
    id: 24,
    question: "The Feast of Weeks, fifty days after Passover, is also known by which Greek name?",
    options: ["Hanukkah", "Pentecost", "Purim", "Epiphany"],
    answer: 1,
    explanation: "Shavuot, the Feast of Weeks, is called Pentecost (“fiftieth”).",
    reference: "Leviticus 23:15-16",
  },
  {
    id: 25,
    question: "On the Day of Atonement, what was done with the second goat — the “scapegoat”?",
    options: ["It was sacrificed", "It was sent into the wilderness bearing the people’s sins", "It was given to the priests", "It was burned outside the camp"],
    answer: 1,
    explanation: "The scapegoat was driven into the wilderness, symbolically carrying away sin.",
    reference: "Leviticus 16:21-22",
  },
  {
    id: 26,
    question: "Which feast required Israel to live in temporary booths to remember the wilderness journey?",
    options: ["Firstfruits", "Tabernacles (Booths)", "Trumpets", "Passover"],
    answer: 1,
    explanation: "The Feast of Tabernacles recalled Israel dwelling in booths in the wilderness.",
    reference: "Leviticus 23:42-43",
  },
  {
    id: 27,
    question: "The Feast of Trumpets (Rosh Hashanah) falls in which month of the Hebrew sacred calendar?",
    options: ["The first month", "The third month", "The seventh month", "The twelfth month"],
    answer: 2,
    explanation: "The Feast of Trumpets was held on the first day of the seventh month.",
    reference: "Leviticus 23:24",
  },
  {
    id: 28,
    question: "Which later festival, not in the Law of Moses, celebrates the rededication of the temple and is mentioned in John?",
    options: ["Purim", "Dedication (Hanukkah)", "Jubilee", "Firstfruits"],
    answer: 1,
    explanation: "John records Jesus at the Feast of Dedication in winter.",
    reference: "John 10:22",
  },
  {
    id: 29,
    question: "Every fiftieth year in Israel, when liberty was proclaimed and land returned, was called what?",
    options: ["The Sabbath year", "The Year of Jubilee", "The Feast of Booths", "The Day of Atonement"],
    answer: 1,
    explanation: "The Jubilee proclaimed liberty and the restoration of inheritances.",
    reference: "Leviticus 25:10",
  },
  {
    id: 30,
    question: "The doctrine that God exists as three persons — Father, Son, and Holy Spirit — in one being is called what?",
    options: ["Monotheism", "The Trinity", "The Incarnation", "The Hypostatic union"],
    answer: 1,
    explanation: "Scripture presents one God in three persons; baptism is in the name of all three.",
    reference: "Matthew 28:19",
  },
  {
    id: 31,
    question: "The teaching that the Word “became flesh” — God taking on human nature in Jesus — is known as the:",
    options: ["Atonement", "Incarnation", "Resurrection", "Justification"],
    answer: 1,
    explanation: "The Incarnation is God the Son becoming man.",
    reference: "John 1:14",
  },
  {
    id: 32,
    question: "In Pauline theology, being declared righteous before God through faith is termed:",
    options: ["Sanctification", "Justification", "Glorification", "Reconciliation"],
    answer: 1,
    explanation: "Justification is God declaring the believer righteous by faith.",
    reference: "Romans 5:1",
  },
  {
    id: 33,
    question: "The ongoing process by which a believer is made more holy after conversion is called:",
    options: ["Justification", "Sanctification", "Predestination", "Redemption"],
    answer: 1,
    explanation: "Sanctification is being progressively set apart and made holy.",
    reference: "1 Thessalonians 4:3",
  },
  {
    id: 34,
    question: "Which term describes salvation as a free, unmerited gift of God, not earned by works?",
    options: ["Law", "Grace", "Merit", "Penance"],
    answer: 1,
    explanation: "Salvation is by grace through faith, not of works.",
    reference: "Ephesians 2:8-9",
  },
  {
    id: 35,
    question: "The biblical word meaning to “buy back” or pay a price to free someone from bondage is:",
    options: ["Propitiation", "Redemption", "Adoption", "Sanctification"],
    answer: 1,
    explanation: "Redemption is being purchased out of slavery to sin by Christ’s blood.",
    reference: "1 Peter 1:18-19",
  },
  {
    id: 36,
    question: "Which term means the turning away of God’s wrath through a satisfying sacrifice?",
    options: ["Reconciliation", "Propitiation", "Regeneration", "Imputation"],
    answer: 1,
    explanation: "Christ is the propitiation that satisfies divine justice for sin.",
    reference: "Romans 3:25",
  },
  {
    id: 37,
    question: "On which mountain did Moses die after viewing the Promised Land?",
    options: ["Mount Sinai", "Mount Nebo", "Mount Hermon", "Mount Tabor"],
    answer: 1,
    explanation: "Moses viewed Canaan from Mount Nebo and died there.",
    reference: "Deuteronomy 34:1-5",
  },
  {
    id: 38,
    question: "Which river did Israel cross to enter the Promised Land under Joshua?",
    options: ["The Nile", "The Jordan", "The Euphrates", "The Tigris"],
    answer: 1,
    explanation: "The Jordan parted and Israel crossed on dry ground into Canaan.",
    reference: "Joshua 3:14-17",
  },
  {
    id: 39,
    question: "The city of Caesarea Philippi, where Peter confessed Christ, lay near the foot of which mountain?",
    options: ["Mount Carmel", "Mount Hermon", "Mount Gilboa", "Mount Tabor"],
    answer: 1,
    explanation: "Caesarea Philippi sat at the base of Mount Hermon in the far north.",
    reference: "Matthew 16:13",
  },
  {
    id: 40,
    question: "Which sea (lake) is the lowest body of water on earth and receives the Jordan?",
    options: ["Sea of Galilee", "The Dead Sea", "The Mediterranean", "The Red Sea"],
    answer: 1,
    explanation: "The Dead Sea, fed by the Jordan, is the lowest point on the earth’s surface.",
    reference: "Genesis 14:3",
  },
  {
    id: 41,
    question: "To which island was the apostle John exiled, where he received the Revelation?",
    options: ["Crete", "Patmos", "Cyprus", "Malta"],
    answer: 1,
    explanation: "John was on Patmos when he received the visions of Revelation.",
    reference: "Revelation 1:9",
  },
  {
    id: 42,
    question: "The seven churches of Revelation were located in which Roman province?",
    options: ["Macedonia", "Asia (Asia Minor)", "Achaia", "Galatia"],
    answer: 1,
    explanation: "The seven churches — Ephesus, Smyrna, and so on — were in the province of Asia.",
    reference: "Revelation 1:11",
  },
  {
    id: 43,
    question: "Mount Carmel, the site of Elijah’s contest with Baal’s prophets, overlooks which body of water?",
    options: ["The Dead Sea", "The Mediterranean Sea", "The Sea of Galilee", "The Red Sea"],
    answer: 1,
    explanation: "Mount Carmel rises near the Mediterranean coast of Israel.",
    reference: "1 Kings 18:42-44",
  },
  {
    id: 44,
    question: "In Daniel’s vision of the statue, what material were the legs that represent a later empire?",
    options: ["Gold", "Silver", "Bronze", "Iron"],
    answer: 3,
    explanation: "The iron legs symbolized a strong, crushing kingdom (commonly identified as Rome).",
    reference: "Daniel 2:40",
  },
  {
    id: 45,
    question: "How many seals are opened on the scroll in the book of Revelation?",
    options: ["Three", "Seven", "Ten", "Twelve"],
    answer: 1,
    explanation: "The Lamb opens seven seals, unleashing successive judgments.",
    reference: "Revelation 5:1; 6:1",
  },
  {
    id: 46,
    question: "What is the name of the final battle gathering described in Revelation?",
    options: ["Gog", "Armageddon", "Megiddo Pass", "Sheol"],
    answer: 1,
    explanation: "The kings of the earth gather at Armageddon for the great day of God.",
    reference: "Revelation 16:16",
  },
  {
    id: 47,
    question: "According to Revelation, how long is the period during which Satan is bound before the final judgment?",
    options: ["Seven years", "A thousand years", "Forty years", "Three and a half years"],
    answer: 1,
    explanation: "Satan is bound for a thousand years (the millennium) in John’s vision.",
    reference: "Revelation 20:2-3",
  },
  {
    id: 48,
    question: "What does Paul say will happen to living believers at Christ’s coming, after the dead in Christ rise?",
    options: ["They remain on earth", "They are caught up together in the clouds to meet the Lord", "They sleep first", "They are judged immediately"],
    answer: 1,
    explanation: "The living are caught up with the risen dead to meet the Lord in the air.",
    reference: "1 Thessalonians 4:16-17",
  },
  {
    id: 49,
    question: "In Revelation, what comes down out of heaven as the dwelling of God with His people in the end?",
    options: ["A temple", "The New Jerusalem", "A throne", "The ark"],
    answer: 1,
    explanation: "The holy city, New Jerusalem, descends as God’s eternal dwelling with humanity.",
    reference: "Revelation 21:2-3",
  },
  {
    id: 50,
    question: "Which Old Testament prophet describes the resurrection as “many who sleep in the dust” awaking, some to everlasting life?",
    options: ["Isaiah", "Ezekiel", "Daniel", "Zechariah"],
    answer: 2,
    explanation: "Daniel gives one of the clearest Old Testament statements of bodily resurrection.",
    reference: "Daniel 12:2",
  },
];
