// Beginner-level Bible quiz question bank (50 questions).
// Source: provided "Bible Quiz Beginner" document. Static, no AI calls.
import type { QuizQuestion } from "./types";

export const BEGINNER_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "How many days did God take to create the world before He rested?",
    options: ["5", "6", "7", "8"],
    answer: 1,
    explanation: "Creation was completed in six days, and God saw that it was very good.",
    reference: "Genesis 1:31",
  },
  {
    id: 2,
    question: "What did God create on the very first day?",
    options: ["Animals", "Light", "Stars", "Man"],
    answer: 1,
    explanation: "God said, “Let there be light,” and there was light.",
    reference: "Genesis 1:3",
  },
  {
    id: 3,
    question: "Who were the first man and woman?",
    options: ["Cain and Abel", "Adam and Eve", "Noah and his wife", "Abraham and Sarah"],
    answer: 1,
    explanation: "God formed Adam from the dust and made Eve from his rib.",
    reference: "Genesis 2:7, 22",
  },
  {
    id: 4,
    question: "In which garden did God place Adam and Eve?",
    options: ["Gethsemane", "Eden", "Babylon", "Canaan"],
    answer: 1,
    explanation: "The Lord planted a garden in Eden and placed the man there.",
    reference: "Genesis 2:8",
  },
  {
    id: 5,
    question: "What did God do on the seventh day?",
    options: ["Created the sea", "Rested", "Created light", "Created birds"],
    answer: 1,
    explanation: "God rested from all His work and blessed the seventh day.",
    reference: "Genesis 2:2",
  },
  {
    id: 6,
    question: "Which tree were Adam and Eve forbidden to eat from?",
    options: ["The tree of life", "The tree of knowledge of good and evil", "A fig tree", "An olive tree"],
    answer: 1,
    explanation: "God warned that eating from it would bring death.",
    reference: "Genesis 2:17",
  },
  {
    id: 7,
    question: "Which creature deceived Eve in the garden?",
    options: ["A lion", "A serpent", "A goat", "A donkey"],
    answer: 1,
    explanation: "The serpent was more crafty than any beast and tempted Eve.",
    reference: "Genesis 3:1",
  },
  {
    id: 8,
    question: "Who built an ark at God’s command?",
    options: ["Moses", "Noah", "David", "Abraham"],
    answer: 1,
    explanation: "Noah obeyed God and built the ark to save his household from the flood.",
    reference: "Genesis 6:14",
  },
  {
    id: 9,
    question: "How many people were saved inside the ark?",
    options: ["2", "4", "8", "12"],
    answer: 2,
    explanation: "Noah, his wife, his three sons and their wives — eight in all.",
    reference: "Genesis 7:13; 1 Peter 3:20",
  },
  {
    id: 10,
    question: "How many days and nights did the rain fall during the flood?",
    options: ["7", "40", "100", "150"],
    answer: 1,
    explanation: "The rain fell upon the earth for forty days and forty nights.",
    reference: "Genesis 7:12",
  },
  {
    id: 11,
    question: "What sign sealed God’s promise never to flood the whole earth again?",
    options: ["A star", "A rainbow", "A dove", "An altar"],
    answer: 1,
    explanation: "God set His bow in the cloud as a sign of the covenant.",
    reference: "Genesis 9:13",
  },
  {
    id: 12,
    question: "Which bird returned to Noah carrying an olive leaf?",
    options: ["A raven", "A dove", "A sparrow", "An eagle"],
    answer: 1,
    explanation: "The dove returned with a freshly plucked olive leaf, showing the waters had receded.",
    reference: "Genesis 8:11",
  },
  {
    id: 13,
    question: "What is the first book of the Bible?",
    options: ["Exodus", "Genesis", "Matthew", "Psalms"],
    answer: 1,
    explanation: "Genesis means “beginning” and opens with the creation account.",
    reference: "Genesis 1:1",
  },
  {
    id: 14,
    question: "Whom did God call to leave his country for a land He would show him?",
    options: ["Moses", "Abraham", "Joseph", "Lot"],
    answer: 1,
    explanation: "God called Abram to leave his country, and he obeyed.",
    reference: "Genesis 12:1",
  },
  {
    id: 15,
    question: "What was the name of Abraham’s wife?",
    options: ["Rebekah", "Rachel", "Sarah", "Leah"],
    answer: 2,
    explanation: "God renamed Sarai as Sarah, mother of the promised son.",
    reference: "Genesis 17:15",
  },
  {
    id: 16,
    question: "Which son did God promise to Abraham and Sarah in their old age?",
    options: ["Ishmael", "Isaac", "Jacob", "Esau"],
    answer: 1,
    explanation: "Sarah bore Isaac in her old age, just as God had promised.",
    reference: "Genesis 21:2-3",
  },
  {
    id: 17,
    question: "Whom did God ask Abraham to offer as a test of faith?",
    options: ["Ishmael", "Isaac", "Jacob", "A ram"],
    answer: 1,
    explanation: "God tested Abraham, then provided a ram in Isaac’s place.",
    reference: "Genesis 22:2, 13",
  },
  {
    id: 18,
    question: "What new name did God give Abram in His covenant with him?",
    options: ["Israel", "Abraham", "Abimelech", "Isaac"],
    answer: 1,
    explanation: "Abram became Abraham, “father of many nations.”",
    reference: "Genesis 17:5",
  },
  {
    id: 19,
    question: "Which baby was hidden in a basket on the Nile River?",
    options: ["David", "Moses", "Samuel", "Joseph"],
    answer: 1,
    explanation: "Moses’ mother hid him in a basket among the reeds of the Nile.",
    reference: "Exodus 2:3",
  },
  {
    id: 20,
    question: "Who drew Moses out of the river and raised him?",
    options: ["His mother", "Pharaoh’s daughter", "Miriam", "A maidservant"],
    answer: 1,
    explanation: "Pharaoh’s daughter found the baby and raised him as her son.",
    reference: "Exodus 2:5-10",
  },
  {
    id: 21,
    question: "Who was Moses’ brother and spokesman?",
    options: ["Aaron", "Joshua", "Caleb", "Hur"],
    answer: 0,
    explanation: "God appointed Aaron to speak for Moses before Pharaoh.",
    reference: "Exodus 4:14-16",
  },
  {
    id: 22,
    question: "From what did God first speak to Moses on the mountain?",
    options: ["A cloud", "A burning bush", "A whirlwind", "A pillar of salt"],
    answer: 1,
    explanation: "God spoke from a bush that burned but was not consumed.",
    reference: "Exodus 3:2",
  },
  {
    id: 23,
    question: "How many plagues did God send upon Egypt?",
    options: ["7", "10", "12", "3"],
    answer: 1,
    explanation: "Ten plagues struck Egypt until Pharaoh let Israel go.",
    reference: "Exodus 7–12",
  },
  {
    id: 24,
    question: "Which sea did God divide so Israel could cross on dry ground?",
    options: ["The Jordan", "The Red Sea", "The Sea of Galilee", "The Dead Sea"],
    answer: 1,
    explanation: "God parted the Red Sea, and Israel crossed on dry land.",
    reference: "Exodus 14:21-22",
  },
  {
    id: 25,
    question: "What bread-like food did God rain from heaven in the wilderness?",
    options: ["Quail", "Manna", "Honey", "Figs"],
    answer: 1,
    explanation: "God provided manna each morning to feed His people.",
    reference: "Exodus 16:14-15",
  },
  {
    id: 26,
    question: "On which mountain did Moses receive the Ten Commandments?",
    options: ["Carmel", "Sinai", "Zion", "Olives"],
    answer: 1,
    explanation: "God gave the Law to Moses on Mount Sinai.",
    reference: "Exodus 19:20; 20:1",
  },
  {
    id: 27,
    question: "How many commandments did God give through Moses?",
    options: ["5", "7", "10", "12"],
    answer: 2,
    explanation: "God wrote ten commandments on two tablets of stone.",
    reference: "Exodus 20:1-17",
  },
  {
    id: 28,
    question: "Which is the first of the Ten Commandments?",
    options: ["Do not steal", "Have no other gods before God", "Keep the Sabbath", "Do not lie"],
    answer: 1,
    explanation: "The first commandment calls for exclusive worship of the one true God.",
    reference: "Exodus 20:3",
  },
  {
    id: 29,
    question: "Which commandment tells us to honor our father and mother?",
    options: ["The third", "The fifth", "The seventh", "The ninth"],
    answer: 1,
    explanation: "Honoring parents is the fifth commandment, with a promise attached.",
    reference: "Exodus 20:12",
  },
  {
    id: 30,
    question: "Which commandment forbids stealing?",
    options: ["The sixth", "The seventh", "The eighth", "The ninth"],
    answer: 2,
    explanation: "“You shall not steal” is the eighth commandment.",
    reference: "Exodus 20:15",
  },
  {
    id: 31,
    question: "How many years did Israel wander in the wilderness?",
    options: ["7", "12", "40", "70"],
    answer: 2,
    explanation: "Israel wandered forty years until that generation passed.",
    reference: "Numbers 14:33-34",
  },
  {
    id: 32,
    question: "Who led Israel into the Promised Land after Moses died?",
    options: ["Aaron", "Joshua", "Caleb", "Gideon"],
    answer: 1,
    explanation: "God commissioned Joshua to lead Israel across the Jordan.",
    reference: "Joshua 1:1-2",
  },
  {
    id: 33,
    question: "Which young shepherd defeated the giant Goliath?",
    options: ["Saul", "David", "Jonathan", "Samuel"],
    answer: 1,
    explanation: "David trusted God and struck down Goliath.",
    reference: "1 Samuel 17:49-50",
  },
  {
    id: 34,
    question: "What weapon did David use against Goliath?",
    options: ["A sword", "A spear", "A sling and a stone", "A bow"],
    answer: 2,
    explanation: "David felled the giant with a single stone from his sling.",
    reference: "1 Samuel 17:40, 49",
  },
  {
    id: 35,
    question: "To which people did Goliath belong?",
    options: ["Egyptians", "Philistines", "Moabites", "Amalekites"],
    answer: 1,
    explanation: "Goliath was the champion of the Philistine army.",
    reference: "1 Samuel 17:4",
  },
  {
    id: 36,
    question: "Which musical instrument did David play?",
    options: ["Trumpet", "Harp", "Flute", "Drum"],
    answer: 1,
    explanation: "David played the harp, even soothing King Saul with it.",
    reference: "1 Samuel 16:23",
  },
  {
    id: 37,
    question: "Who was the first king of Israel?",
    options: ["David", "Saul", "Samuel", "Solomon"],
    answer: 1,
    explanation: "Samuel anointed Saul as Israel’s first king.",
    reference: "1 Samuel 10:1",
  },
  {
    id: 38,
    question: "Which book contains many of David’s songs and prayers?",
    options: ["Proverbs", "Psalms", "Job", "Genesis"],
    answer: 1,
    explanation: "Many of the Psalms are titled as songs of David.",
    reference: "Psalm 23:1",
  },
  {
    id: 39,
    question: "In which town was Jesus born?",
    options: ["Nazareth", "Bethlehem", "Jerusalem", "Capernaum"],
    answer: 1,
    explanation: "Jesus was born in Bethlehem, the city of David.",
    reference: "Luke 2:4-7",
  },
  {
    id: 40,
    question: "Who was the mother of Jesus?",
    options: ["Martha", "Mary", "Elizabeth", "Anna"],
    answer: 1,
    explanation: "The angel told Mary she would give birth to the Son of God.",
    reference: "Luke 1:30-31",
  },
  {
    id: 41,
    question: "Who baptized Jesus in the Jordan River?",
    options: ["Peter", "John the Baptist", "Andrew", "Paul"],
    answer: 1,
    explanation: "John baptized Jesus, and the Spirit descended like a dove.",
    reference: "Matthew 3:13-16",
  },
  {
    id: 42,
    question: "How many disciples (apostles) did Jesus choose?",
    options: ["7", "10", "12", "70"],
    answer: 2,
    explanation: "Jesus appointed twelve to be with Him and to be sent out.",
    reference: "Matthew 10:1-4",
  },
  {
    id: 43,
    question: "Which two disciples were brothers and sons of Zebedee?",
    options: ["Peter and Andrew", "James and John", "Philip and Thomas", "Matthew and Judas"],
    answer: 1,
    explanation: "James and John, sons of Zebedee, left their fishing nets to follow Jesus.",
    reference: "Matthew 4:21-22",
  },
  {
    id: 44,
    question: "What was Jesus’ first recorded miracle?",
    options: ["Healing a leper", "Turning water into wine", "Walking on water", "Raising Lazarus"],
    answer: 1,
    explanation: "At the wedding in Cana, Jesus turned water into wine.",
    reference: "John 2:1-11",
  },
  {
    id: 45,
    question: "Which disciple betrayed Jesus?",
    options: ["Peter", "Judas Iscariot", "Thomas", "John"],
    answer: 1,
    explanation: "Judas betrayed Jesus for thirty pieces of silver.",
    reference: "Matthew 26:14-16",
  },
  {
    id: 46,
    question: "Which disciple denied Jesus three times?",
    options: ["Peter", "James", "Andrew", "Philip"],
    answer: 0,
    explanation: "Peter denied knowing Jesus three times before the rooster crowed.",
    reference: "Luke 22:54-62",
  },
  {
    id: 47,
    question: "How many days was Jesus in the tomb before He rose?",
    options: ["1", "2", "3", "7"],
    answer: 2,
    explanation: "Jesus rose on the third day, just as the Scriptures said.",
    reference: "Luke 24:6-7; 1 Corinthians 15:4",
  },
  {
    id: 48,
    question: "What was the name of the place where Jesus was crucified?",
    options: ["Bethlehem", "Golgotha", "Galilee", "Bethany"],
    answer: 1,
    explanation: "Golgotha means “the place of a skull,” where Jesus was crucified.",
    reference: "Matthew 27:33",
  },
  {
    id: 49,
    question: "What sign of the covenant did God give Abraham for his household?",
    options: ["A rainbow", "Circumcision", "The Sabbath", "Passover"],
    answer: 1,
    explanation: "Circumcision was the covenant sign for Abraham and his descendants.",
    reference: "Genesis 17:10-11",
  },
  {
    id: 50,
    question: "Who was the oldest man recorded in the Bible, living 969 years?",
    options: ["Adam", "Noah", "Methuselah", "Enoch"],
    answer: 2,
    explanation: "Methuselah lived 969 years, longer than anyone else recorded in Scripture.",
    reference: "Genesis 5:27",
  },
];
