// Intermediate-level Bible quiz question bank (50 questions).
// Source: provided "Bible Quiz Intermediate" document. Static, no AI calls.
import type { QuizQuestion } from "./types";

export const INTERMEDIATE_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "Who succeeded David as king of Israel?",
    options: ["Absalom", "Solomon", "Adonijah", "Rehoboam"],
    answer: 1,
    explanation: "Solomon, son of David and Bathsheba, became king and built the temple.",
    reference: "1 Kings 2:12",
  },
  {
    id: 2,
    question: "After Solomon’s death, the kingdom split in two. Who led the northern tribes away from Rehoboam?",
    options: ["Jeroboam", "Jehu", "Omri", "Baasha"],
    answer: 0,
    explanation: "Jeroboam led the ten northern tribes to form the kingdom of Israel.",
    reference: "1 Kings 12:20",
  },
  {
    id: 3,
    question: "Which king of Israel married Jezebel and promoted Baal worship?",
    options: ["Ahaz", "Ahab", "Jehoram", "Jehu"],
    answer: 1,
    explanation: "Ahab married Jezebel of Sidon and led Israel into Baal worship.",
    reference: "1 Kings 16:31",
  },
  {
    id: 4,
    question: "Which king of Judah was only seven years old when he began to reign?",
    options: ["Josiah", "Joash", "Uzziah", "Hezekiah"],
    answer: 1,
    explanation: "Joash (Jehoash) was hidden as a child and crowned at age seven.",
    reference: "2 Kings 11:21",
  },
  {
    id: 5,
    question: "Which king of Judah added fifteen years to his life after praying when he was ill?",
    options: ["Hezekiah", "Josiah", "Asa", "Jotham"],
    answer: 0,
    explanation: "God healed Hezekiah and gave him fifteen more years, with the sun’s shadow as a sign.",
    reference: "2 Kings 20:5-6",
  },
  {
    id: 6,
    question: "Which king of Judah found the Book of the Law during temple repairs and led a great reform?",
    options: ["Hezekiah", "Josiah", "Manasseh", "Jehoshaphat"],
    answer: 1,
    explanation: "Josiah renewed the covenant after the rediscovered Law was read to him.",
    reference: "2 Kings 22:8-11",
  },
  {
    id: 7,
    question: "Which prophet was taken up to heaven in a whirlwind by a chariot of fire?",
    options: ["Elisha", "Elijah", "Enoch", "Isaiah"],
    answer: 1,
    explanation: "Elijah was carried up in a whirlwind, and Elisha received a double portion of his spirit.",
    reference: "2 Kings 2:11",
  },
  {
    id: 8,
    question: "Which prophet confronted the prophets of Baal on Mount Carmel?",
    options: ["Elisha", "Elijah", "Micaiah", "Nathan"],
    answer: 1,
    explanation: "Elijah called down fire from heaven, exposing Baal’s prophets as powerless.",
    reference: "1 Kings 18:36-39",
  },
  {
    id: 9,
    question: "Which prophet was called to marry Gomer, an unfaithful wife, as a living picture of Israel’s unfaithfulness?",
    options: ["Hosea", "Amos", "Joel", "Micah"],
    answer: 0,
    explanation: "Hosea’s marriage symbolized God’s faithful love for unfaithful Israel.",
    reference: "Hosea 1:2-3",
  },
  {
    id: 10,
    question: "Which prophet saw a vision of the Lord on a throne, with seraphim crying “Holy, holy, holy”?",
    options: ["Jeremiah", "Ezekiel", "Isaiah", "Daniel"],
    answer: 2,
    explanation: "Isaiah’s temple vision led to his cleansing and commissioning.",
    reference: "Isaiah 6:1-8",
  },
  {
    id: 11,
    question: "Which prophet was lowered into a muddy cistern for his unpopular message?",
    options: ["Jeremiah", "Ezekiel", "Habakkuk", "Nahum"],
    answer: 0,
    explanation: "Jeremiah was thrown into a cistern but rescued by Ebed-Melech.",
    reference: "Jeremiah 38:6",
  },
  {
    id: 12,
    question: "Which prophet saw the valley of dry bones come to life?",
    options: ["Isaiah", "Daniel", "Ezekiel", "Zechariah"],
    answer: 2,
    explanation: "Ezekiel prophesied over dry bones that rose as a vast army, picturing Israel’s revival.",
    reference: "Ezekiel 37:1-10",
  },
  {
    id: 13,
    question: "Through which prophet did Naaman the Syrian commander get healed of leprosy?",
    options: ["Elijah", "Elisha", "Isaiah", "Nathan"],
    answer: 1,
    explanation: "Elisha told Naaman to wash seven times in the Jordan, and he was healed.",
    reference: "2 Kings 5:10-14",
  },
  {
    id: 14,
    question: "In the parable of the sower, what do the seeds that fell on rocky ground represent?",
    options: ["Those who never hear", "Those who receive the word with joy but fall away under trouble", "The fruitful believers", "Those choked by riches"],
    answer: 1,
    explanation: "Rocky-ground hearers have no root and stumble when persecution comes.",
    reference: "Matthew 13:20-21",
  },
  {
    id: 15,
    question: "In the parable of the prodigal son, what did the father do when he saw his son returning?",
    options: ["Scolded him", "Ran to him and embraced him", "Ignored him", "Sent a servant"],
    answer: 1,
    explanation: "Filled with compassion, the father ran, embraced, and celebrated his son’s return.",
    reference: "Luke 15:20",
  },
  {
    id: 16,
    question: "In the parable of the Good Samaritan, who passed by the wounded man before the Samaritan helped?",
    options: ["A priest and a Levite", "Two soldiers", "A tax collector", "A Pharisee and a scribe"],
    answer: 0,
    explanation: "Both a priest and a Levite passed by; only the Samaritan showed mercy.",
    reference: "Luke 10:31-33",
  },
  {
    id: 17,
    question: "In the parable of the talents, what happened to the servant who buried his one talent?",
    options: ["He was praised", "His talent was taken and given to the one with ten", "He was forgiven", "He earned interest"],
    answer: 1,
    explanation: "The unprofitable servant lost his talent and was cast out.",
    reference: "Matthew 25:28-30",
  },
  {
    id: 18,
    question: "The parable of the ten virgins teaches readiness. What separated the wise from the foolish?",
    options: ["Their clothing", "Oil for their lamps", "Their age", "Arriving first"],
    answer: 1,
    explanation: "The wise brought extra oil and were ready when the bridegroom came.",
    reference: "Matthew 25:3-4",
  },
  {
    id: 19,
    question: "In the parable of the unforgiving servant, why was the servant thrown into prison?",
    options: ["He stole money", "He refused to forgive a small debt after being forgiven a huge one", "He lied to the king", "He fled the country"],
    answer: 1,
    explanation: "Forgiven a vast debt, he jailed a fellow servant over a tiny one.",
    reference: "Matthew 18:28-34",
  },
  {
    id: 20,
    question: "At which pool did Jesus heal a man who had been an invalid for thirty-eight years?",
    options: ["Siloam", "Bethesda", "Gibeon", "Solomon’s Porch"],
    answer: 1,
    explanation: "Jesus healed the long-paralyzed man at the pool of Bethesda.",
    reference: "John 5:5-9",
  },
  {
    id: 21,
    question: "When Jesus fed the five thousand, what did the boy’s lunch consist of?",
    options: ["Five loaves and two fish", "Seven loaves", "Three loaves and a fish", "Bread and wine"],
    answer: 0,
    explanation: "From five loaves and two fish, Jesus fed the multitude with leftovers to spare.",
    reference: "John 6:9-13",
  },
  {
    id: 22,
    question: "Whom did Jesus raise from the dead after he had been in the tomb four days?",
    options: ["Jairus’ daughter", "The widow’s son at Nain", "Lazarus", "Tabitha"],
    answer: 2,
    explanation: "Jesus called Lazarus out of the tomb after four days, displaying His power over death.",
    reference: "John 11:39-44",
  },
  {
    id: 23,
    question: "What did Jesus do when caught in a storm on the Sea of Galilee with His disciples?",
    options: ["Swam ashore", "Rebuked the wind and waves to calm them", "Woke a fisherman", "Turned the boat around"],
    answer: 1,
    explanation: "Jesus stilled the storm with a word, and the disciples marveled.",
    reference: "Mark 4:39",
  },
  {
    id: 24,
    question: "In Jesus’ first miracle at Cana, how many stone water jars were filled?",
    options: ["Three", "Six", "Seven", "Twelve"],
    answer: 1,
    explanation: "Six stone jars were filled with water that Jesus turned into wine.",
    reference: "John 2:6-7",
  },
  {
    id: 25,
    question: "Which apostle walked on water toward Jesus before he began to sink?",
    options: ["John", "Peter", "James", "Andrew"],
    answer: 1,
    explanation: "Peter walked on the water but sank when he saw the wind and doubted.",
    reference: "Matthew 14:29-30",
  },
  {
    id: 26,
    question: "What was Saul (Paul) doing on the road to Damascus when he encountered the risen Christ?",
    options: ["Preaching the gospel", "Going to arrest Christians", "Returning home", "Collecting taxes"],
    answer: 1,
    explanation: "Saul was on his way to persecute believers when a light from heaven stopped him.",
    reference: "Acts 9:1-4",
  },
  {
    id: 27,
    question: "In which city were the disciples first called “Christians”?",
    options: ["Jerusalem", "Antioch", "Ephesus", "Corinth"],
    answer: 1,
    explanation: "It was at Antioch that the disciples were first called Christians.",
    reference: "Acts 11:26",
  },
  {
    id: 28,
    question: "Who traveled with Paul on his first missionary journey?",
    options: ["Silas", "Barnabas", "Timothy", "Luke"],
    answer: 1,
    explanation: "Barnabas accompanied Paul (with John Mark) on the first journey from Antioch.",
    reference: "Acts 13:2-5",
  },
  {
    id: 29,
    question: "In Philippi, what happened after Paul and Silas sang hymns in prison at midnight?",
    options: ["The guards fled", "An earthquake opened the prison doors", "They were freed by a judge", "A storm struck"],
    answer: 1,
    explanation: "An earthquake shook the prison, and the jailer was converted that night.",
    reference: "Acts 16:25-34",
  },
  {
    id: 30,
    question: "In Athens, where did Paul preach about the “unknown god”?",
    options: ["The temple", "The Areopagus (Mars’ Hill)", "The marketplace stalls", "Caesar’s court"],
    answer: 1,
    explanation: "Paul reasoned with the philosophers at the Areopagus about the unknown God.",
    reference: "Acts 17:22-23",
  },
  {
    id: 31,
    question: "On which island was Paul shipwrecked on his way to Rome, where a viper bit him?",
    options: ["Cyprus", "Crete", "Malta", "Patmos"],
    answer: 2,
    explanation: "Paul was shipwrecked on Malta and shook off a viper unharmed.",
    reference: "Acts 28:1-5",
  },
  {
    id: 32,
    question: "Which letter contains the “fruit of the Spirit” — love, joy, peace, patience, and so on?",
    options: ["Ephesians", "Galatians", "Philippians", "Colossians"],
    answer: 1,
    explanation: "Paul lists the fruit of the Spirit in his letter to the Galatians.",
    reference: "Galatians 5:22-23",
  },
  {
    id: 33,
    question: "Which letter, often called the “epistle of joy,” was written by Paul from prison?",
    options: ["Romans", "Philippians", "Titus", "Hebrews"],
    answer: 1,
    explanation: "Paul wrote Philippians in chains, yet it overflows with rejoicing.",
    reference: "Philippians 4:4",
  },
  {
    id: 34,
    question: "The famous “love chapter” (“Love is patient, love is kind…”) is found in which book?",
    options: ["Romans", "1 Corinthians", "Ephesians", "1 John"],
    answer: 1,
    explanation: "1 Corinthians 13 is Paul’s great description of love.",
    reference: "1 Corinthians 13:4",
  },
  {
    id: 35,
    question: "In which letter does Paul describe the full “armor of God”?",
    options: ["Ephesians", "Colossians", "2 Timothy", "Romans"],
    answer: 0,
    explanation: "Paul urges believers to put on the whole armor of God in Ephesians 6.",
    reference: "Ephesians 6:11-17",
  },
  {
    id: 36,
    question: "Which short letter did Paul write appealing for the runaway slave Onesimus?",
    options: ["Titus", "Philemon", "Jude", "Philippians"],
    answer: 1,
    explanation: "Paul appealed to Philemon to receive Onesimus back as a brother.",
    reference: "Philemon 1:10-16",
  },
  {
    id: 37,
    question: "To whom did Paul write, “Let no one despise your youth, but set an example”?",
    options: ["Titus", "Timothy", "Philemon", "Silas"],
    answer: 1,
    explanation: "Paul encouraged the young pastor Timothy to be an example in word and conduct.",
    reference: "1 Timothy 4:12",
  },
  {
    id: 38,
    question: "Who was the cupbearer to the king of Persia who rebuilt Jerusalem’s walls?",
    options: ["Ezra", "Nehemiah", "Mordecai", "Zerubbabel"],
    answer: 1,
    explanation: "Nehemiah, the king’s cupbearer, led the rebuilding of Jerusalem’s walls.",
    reference: "Nehemiah 2:1, 17",
  },
  {
    id: 39,
    question: "Which Jewish queen risked her life to save her people from Haman’s plot?",
    options: ["Vashti", "Esther", "Deborah", "Bathsheba"],
    answer: 1,
    explanation: "Esther approached the king uninvited and exposed Haman’s scheme.",
    reference: "Esther 4:16; 7:6",
  },
  {
    id: 40,
    question: "Who was the tax collector that climbed a sycamore tree to see Jesus?",
    options: ["Matthew", "Zacchaeus", "Levi", "Nicodemus"],
    answer: 1,
    explanation: "Zacchaeus, a chief tax collector, climbed a tree and Jesus dined at his house.",
    reference: "Luke 19:2-5",
  },
  {
    id: 41,
    question: "Which couple in Acts fell dead for lying to the Holy Spirit about their offering?",
    options: ["Aquila and Priscilla", "Ananias and Sapphira", "Felix and Drusilla", "Boaz and Ruth"],
    answer: 1,
    explanation: "Ananias and Sapphira lied about their gift and died as a warning to the church.",
    reference: "Acts 5:1-10",
  },
  {
    id: 42,
    question: "Who was the Pharisee and teacher who came to Jesus by night and heard “you must be born again”?",
    options: ["Gamaliel", "Nicodemus", "Joseph of Arimathea", "Caiaphas"],
    answer: 1,
    explanation: "Jesus told Nicodemus that one must be born again to see the kingdom of God.",
    reference: "John 3:1-7",
  },
  {
    id: 43,
    question: "Which judge of Israel defeated the Midianites with just 300 men?",
    options: ["Samson", "Gideon", "Ehud", "Barak"],
    answer: 1,
    explanation: "Gideon’s 300, with trumpets and torches, routed the Midianite host.",
    reference: "Judges 7:7, 20-21",
  },
  {
    id: 44,
    question: "Where is found: “For God so loved the world, that he gave his only begotten Son…”?",
    options: ["John 3:16", "Romans 5:8", "1 John 4:9", "John 1:14"],
    answer: 0,
    explanation: "This best-known summary of the gospel is John 3:16.",
    reference: "John 3:16",
  },
  {
    id: 45,
    question: "Where is found: “The LORD is my shepherd; I shall not want”?",
    options: ["Psalm 23:1", "Psalm 91:1", "Psalm 100:3", "Isaiah 40:11"],
    answer: 0,
    explanation: "The opening line of the shepherd psalm is Psalm 23:1.",
    reference: "Psalm 23:1",
  },
  {
    id: 46,
    question: "Where is found: “I can do all things through Christ who strengthens me”?",
    options: ["Romans 8:37", "Philippians 4:13", "2 Corinthians 12:9", "Ephesians 3:20"],
    answer: 1,
    explanation: "Paul’s declaration of contented strength is Philippians 4:13.",
    reference: "Philippians 4:13",
  },
  {
    id: 47,
    question: "Where is found: “Trust in the LORD with all your heart, and lean not on your own understanding”?",
    options: ["Psalm 37:5", "Proverbs 3:5", "Jeremiah 29:11", "Isaiah 26:3"],
    answer: 1,
    explanation: "This call to wholehearted trust is Proverbs 3:5.",
    reference: "Proverbs 3:5",
  },
  {
    id: 48,
    question: "Where is found: “In the beginning was the Word, and the Word was with God, and the Word was God”?",
    options: ["Genesis 1:1", "John 1:1", "Colossians 1:16", "Hebrews 1:1"],
    answer: 1,
    explanation: "John’s prologue about the eternal Word is John 1:1.",
    reference: "John 1:1",
  },
  {
    id: 49,
    question: "Where is found: “For all have sinned, and come short of the glory of God”?",
    options: ["Romans 3:23", "Romans 6:23", "Isaiah 53:6", "1 John 1:8"],
    answer: 0,
    explanation: "Paul’s statement of universal sin is Romans 3:23.",
    reference: "Romans 3:23",
  },
  {
    id: 50,
    question: "Where is found: “For I know the plans I have for you… plans to prosper you and not to harm you”?",
    options: ["Jeremiah 29:11", "Isaiah 41:10", "Proverbs 16:9", "Romans 8:28"],
    answer: 0,
    explanation: "God’s promise of a future and a hope is Jeremiah 29:11.",
    reference: "Jeremiah 29:11",
  },
];
